# Generated by Django 5.2.6 on 2025-09-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0020_vacancy_with_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='required_people_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Требуемое количество человек'),
        ),
    ]
