# Generated by Django 5.2.6 on 2025-09-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0021_vacancy_required_people_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код языка (en, ru, pl и тд.)')),
                ('name', models.CharField(max_length=100, verbose_name='Название языка (English, Русский, Polski и тд.)')),
            ],
            options={
                'verbose_name': 'Язык общения',
                'verbose_name_plural': 'Языки общения',
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='communication_languages',
            field=models.ManyToManyField(blank=True, to='vacancy.language', verbose_name='Языки общения'),
        ),
    ]
