# Generated by Django 5.2.6 on 2025-09-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0022_language_vacancy_communication_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='name_az',
            field=models.CharField(max_length=100, null=True, verbose_name='Название языка (English, Русский, Polski и тд.)'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название языка (English, Русский, Polski и тд.)'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_pl',
            field=models.CharField(max_length=100, null=True, verbose_name='Название языка (English, Русский, Polski и тд.)'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название языка (English, Русский, Polski и тд.)'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Название языка (English, Русский, Polski и тд.)'),
        ),
    ]
